name: Build Reacher Backend

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - name: Build Release
        run: |
          cd backend
          cargo build --release --bin reacher_backend

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: reacher-backend-windows
          path: |
            backend/target/release/reacher_backend.exe
            backend/target/release/reacher_backend.pdb
          retention-days: 5
