name: Build Reacher Backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # Install Rust + Windows target
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          profile: minimal
          override: true

      # Build the backend specifically
      - name: Build Backend
        run: |
          cd backend
          cargo build --release --bin reacher_backend

      # Upload the .exe as an artifact
      - uses: actions/upload-artifact@v3
        with:
          name: reacher-backend-windows
          path: backend/target/release/reacher_backend.exe
